# Generated by Django 5.1.4 on 2025-03-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorSuhuACData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ppm', models.FloatField()),
                ('temp', models.FloatField()),
                ('humi', models.FloatField()),
                ('tempout', models.FloatField()),
                ('humiout', models.FloatField()),
                ('tempac', models.FloatField()),
                ('modeac', models.FloatField()),
                ('hasilpred', models.FloatField()),
            ],
        ),
    ]
