# Generated by Django 5.1.4 on 2025-03-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorSuhuACData',
            new_name='SensorSmartACData',
        ),
    ]
