# Generated by Django 5.1.4 on 2025-03-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0002_rename_sensorsuhuacdata_sensorsmartacdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorsmartacdata',
            name='humi',
        ),
        migrations.RemoveField(
            model_name='sensorsmartacdata',
            name='ppm',
        ),
        migrations.RemoveField(
            model_name='sensorsmartacdata',
            name='temp',
        ),
    ]
