# Generated by Django 3.2.12 on 2024-10-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Gambar Name')),
                ('gambar', models.ImageField(blank=True, default='profil.png', upload_to='profiles/', verbose_name='Gambar')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Image Description')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Link Name')),
                ('link', models.URLField(max_length=255, verbose_name='Link')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Additional Info')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Skill Name')),
                ('persentase', models.IntegerField(verbose_name='Skill Percentage')),
                ('tingkat', models.CharField(max_length=50, verbose_name='Skill Level')),
                ('bintang', models.IntegerField(verbose_name='Star Rating')),
                ('subjek', models.CharField(max_length=255, verbose_name='Skill Subject')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Skill Details')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Related Experience')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.image', verbose_name='Skill Image')),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.link', verbose_name='Skill Link')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Project Name')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Project Details')),
                ('letak', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.image', verbose_name='Related Image')),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.link', verbose_name='Related Link')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Experience Name')),
                ('subjek', models.CharField(max_length=255, verbose_name='Subject')),
                ('instansi', models.CharField(max_length=255, verbose_name='Institution')),
                ('periode', models.DateField(verbose_name='Start Date')),
                ('akhir_periode', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Experience Details')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.image', verbose_name='Experience Image')),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.link', verbose_name='Experience Link')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
