# Generated by Django 3.2.12 on 2024-10-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.image', verbose_name='Experience Image'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.link', verbose_name='Experience Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.link', verbose_name='Related Link'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.image', verbose_name='Skill Image'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.link', verbose_name='Skill Link'),
        ),
    ]
