# Generated by Django 3.2.12 on 2024-10-19 03:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20241019_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gambar',
            field=models.ImageField(blank=True, default='profil.png', upload_to='profiles/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='nama',
            field=models.CharField(max_length=255, verbose_name='Image Name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='bintang',
            field=models.IntegerField(help_text='Enter star rating between 1 and 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Star Rating'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.experience', verbose_name='Skill Experience'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='persentase',
            field=models.IntegerField(help_text='Enter percentage value between 0 and 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Skill Percentage'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tingkat',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=50, verbose_name='Skill Level'),
        ),
    ]
