# Generated by Django 3.2.12 on 2024-10-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_experience_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='project',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='experience',
        ),
        migrations.AddField(
            model_name='experience',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.Project', verbose_name='Related Projects'),
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.Skill', verbose_name='Related Skills'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.Skill', verbose_name='Related Skills'),
        ),
    ]
