# Generated by Django 3.2.12 on 2024-10-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_image_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='subjek',
            field=models.CharField(max_length=255, null=True, verbose_name='Link Subject'),
        ),
    ]
