# Generated by Django 3.2.12 on 2024-10-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_link_subjek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='subjek',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Subject'),
        ),
    ]
